### ISSUE TITLE
Add "size" field for modular blueprint dropdown options

### ISSUE THREAD

**Issue by benblee** [smartgravity/grav-theme-bones#4]
The dropdown options for the modular template blueprints are currently full width and would look better if they were sized smaller.

The "**size**" field can be used for this:

```
            header.image_align:
              type: select
              label: Image position
              classes: fancy
              size: small
              default: right
              options:
                'center': 'Center'
                'left': 'Left'
                'right': 'Right'
```
